In [78]:
import pandas as pd

### Что со столбцом days_employed?

In [79]:
data = pd.read_csv('data.csv', delimiter='\t')
data

,children,days_employed,dob_days,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля
20,1,-1311.604166,36,среднее,1,женат / замужем,0,M,сотрудник,0,209552.644578,недвижимость
21,1,-253.685166,33,среднее,1,гражданский брак,1,F,сотрудник,0,131812.203909,приобретение автомобиля
22,1,-1766.644138,24,среднее,1,гражданский брак,1,F,сотрудник,0,149681.140731,на покупку подержанного автомобиля
23,0,-272.981385,21,высшее,0,гражданский брак,1,M,сотрудник,0,128265.720871,сыграть свадьбу
24,1,338551.952911,57,среднее,1,Не женат / не замужем,4,F,пенсионер,0,290547.235997,операции с коммерческой недвижимостью
25,0,363548.489348,67,среднее,1,женат / замужем,0,M,пенсионер,0,55112.757732,покупка недвижимости
26,0,NaN,41,среднее,1,женат / замужем,0,M,госслужащий,0,NaN,образование
27,0,-529.191635,28,высшее,0,женат / замужем,0,M,сотрудник,0,308848.983691,строительство собственной недвижимости
28,1,-717.274324,26,высшее,0,женат / замужем,0,F,сотрудник,0,187863.237306,строительство собственной недвижимости
29,0,NaN,63,среднее,1,Не женат / не замужем,4,F,пенсионер,0,NaN,строительство жилой недвижимости
...,...,...,...,...,...,...,...,...,...,...,...,...
21495,1,NaN,50,среднее,1,гражданский брак,1,F,сотрудник,0,NaN,свадьба
21496,1,-759.680851,31,среднее,1,женат / замужем,0,F,сотрудник,0,119392.620079,на покупку автомобиля
21497,0,NaN,48,ВЫСШЕЕ,0,женат / замужем,0,F,компаньон,0,NaN,строительство недвижимости
21498,1,-1330.627998,32,среднее,1,гражданский брак,1,M,сотрудник,0,240767.575887,сыграть свадьбу
21499,0,-9929.015065,57,среднее,1,гражданский брак,1,M,компаньон,0,157553.158589,свадьба
21500,0,-578.082757,26,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,77813.293365,операции с коммерческой недвижимостью
21501,0,334343.096304,57,среднее,1,женат / замужем,0,F,пенсионер,0,86232.126549,жилье
21502,1,NaN,42,среднее,1,женат / замужем,0,F,сотрудник,0,NaN,строительство жилой недвижимости
21503,0,-3096.881131,58,среднее,1,женат / замужем,0,F,сотрудник,0,264250.997662,заняться образованием
21504,0,355235.728158,68,среднее,1,женат / замужем,0,F,пенсионер,0,80566.321329,дополнительное образование
21505,0,338904.866406,53,среднее,1,гражданский брак,1,M,пенсионер,0,75439.993167,сыграть свадьбу
21506,1,-1556.249906,33,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,145541.993320,свадьба
21507,1,-79.832064,32,среднее,1,гражданский брак,1,F,госслужащий,0,98180.279152,сделка с подержанным автомобилем
21508,0,386497.714078,62,среднее,1,женат / замужем,0,M,пенсионер,0,72638.590915,недвижимость
21509,0,362161.054124,59,высшее,0,женат / замужем,0,M,пенсионер,0,73029.059379,операции с недвижимостью
21510,2,NaN,28,среднее,1,женат / замужем,0,F,сотрудник,0,NaN,приобретение автомобиля
21511,0,-612.569129,29,высшее,0,гражданский брак,1,F,сотрудник,1,140068.472941,покупка жилья для сдачи
21512,0,-165.377752,26,высшее,0,Не женат / не замужем,4,M,компаньон,0,147301.457769,получение дополнительного образования
21513,0,-1166.216789,35,среднее,1,женат / замужем,0,F,сотрудник,0,250986.142309,покупка жилья
21514,0,-280.469996,27,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,355988.407188,строительство недвижимости
21515,1,-467.685130,28,среднее,1,женат / замужем,0,F,сотрудник,1,109486.327999,заняться образованием
21516,0,-914.391429,42,высшее,0,женат / замужем,0,F,компаньон,0,322807.776603,покупка своего жилья
21517,0,-404.679034,42,высшее,0,гражданский брак,1,F,компаньон,0,178059.553491,на покупку своего автомобиля
21518,0,373995.710838,59,СРЕДНЕЕ,1,женат / замужем,0,F,пенсионер,0,153864.650328,сделка с автомобилем
21519,1,-2351.431934,37,ученая степень,4,в разводе,3,M,сотрудник,0,115949.039788,покупка коммерческой недвижимости
21520,1,-4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791.862382,операции с жильем
21521,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999.806512,сделка с автомобилем
21522,1,-2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672.561153,недвижимость
21523,3,-3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093.050500,на покупку своего автомобиля
21524,2,-1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047.418899,на покупку автомобиля

Что со столбцом `days_employed`?

In [80]:
data[data['days_employed'] < 0]

,children,days_employed,dob_days,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля
20,1,-1311.604166,36,среднее,1,женат / замужем,0,M,сотрудник,0,209552.644578,недвижимость
21,1,-253.685166,33,среднее,1,гражданский брак,1,F,сотрудник,0,131812.203909,приобретение автомобиля
22,1,-1766.644138,24,среднее,1,гражданский брак,1,F,сотрудник,0,149681.140731,на покупку подержанного автомобиля
23,0,-272.981385,21,высшее,0,гражданский брак,1,M,сотрудник,0,128265.720871,сыграть свадьбу
27,0,-529.191635,28,высшее,0,женат / замужем,0,M,сотрудник,0,308848.983691,строительство собственной недвижимости
28,1,-717.274324,26,высшее,0,женат / замужем,0,F,сотрудник,0,187863.237306,строительство собственной недвижимости
31,0,-1682.083438,47,начальное,3,женат / замужем,0,F,сотрудник,0,275485.684538,жилье
32,0,-4649.910832,34,СРЕДНЕЕ,1,гражданский брак,1,F,сотрудник,1,139057.464207,на проведение свадьбы
33,0,-1548.637544,48,среднее,1,женат / замужем,0,F,компаньон,0,157245.786233,покупка жилья
34,0,-4488.067031,35,среднее,1,женат / замужем,0,F,сотрудник,0,104660.449203,операции со своей недвижимостью
36,0,-176.216688,33,среднее,1,Не женат / не замужем,4,M,сотрудник,0,138830.650734,автомобили
37,0,-6448.810860,43,ВЫСШЕЕ,0,гражданский брак,1,F,компаньон,0,154128.878672,приобретение автомобиля
38,0,-597.881827,25,высшее,0,Не женат / не замужем,4,M,сотрудник,1,192247.298639,образование
...,...,...,...,...,...,...,...,...,...,...,...,...
21482,1,-865.081118,25,среднее,1,женат / замужем,0,F,компаньон,0,94065.031245,свой автомобиль
21483,2,-2917.035232,38,начальное,3,гражданский брак,1,F,сотрудник,1,77417.560520,операции с недвижимостью
21484,3,-968.718123,35,среднее,1,женат / замужем,0,M,сотрудник,0,95667.452395,жилье
21486,0,-1614.022809,36,СРЕДНЕЕ,1,женат / замужем,0,F,сотрудник,1,80763.856017,автомобиль
21487,0,-2376.789344,30,СРЕДНЕЕ,1,гражданский брак,1,F,сотрудник,0,87834.565090,недвижимость
21488,0,-354.755760,35,высшее,0,Не женат / не замужем,4,F,компаньон,0,128897.486083,недвижимость
21490,2,-1867.006757,32,среднее,1,женат / замужем,0,F,сотрудник,0,34767.965495,операции с коммерческой недвижимостью
21491,20,-173.954460,27,среднее,1,женат / замужем,0,F,сотрудник,0,155520.899688,на покупку подержанного автомобиля
21492,0,-1618.645283,54,среднее,1,женат / замужем,0,M,компаньон,0,295234.214807,покупка жилой недвижимости
21493,1,-1214.858885,38,среднее,1,женат / замужем,0,F,сотрудник,0,147502.599329,покупка жилья для семьи
21494,0,-960.095747,39,среднее,1,гражданский брак,1,M,компаньон,1,176369.594491,дополнительное образование
21496,1,-759.680851,31,среднее,1,женат / замужем,0,F,сотрудник,0,119392.620079,на покупку автомобиля
21498,1,-1330.627998,32,среднее,1,гражданский брак,1,M,сотрудник,0,240767.575887,сыграть свадьбу
21499,0,-9929.015065,57,среднее,1,гражданский брак,1,M,компаньон,0,157553.158589,свадьба
21500,0,-578.082757,26,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,77813.293365,операции с коммерческой недвижимостью
21503,0,-3096.881131,58,среднее,1,женат / замужем,0,F,сотрудник,0,264250.997662,заняться образованием
21506,1,-1556.249906,33,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,145541.993320,свадьба
21507,1,-79.832064,32,среднее,1,гражданский брак,1,F,госслужащий,0,98180.279152,сделка с подержанным автомобилем
21511,0,-612.569129,29,высшее,0,гражданский брак,1,F,сотрудник,1,140068.472941,покупка жилья для сдачи
21512,0,-165.377752,26,высшее,0,Не женат / не замужем,4,M,компаньон,0,147301.457769,получение дополнительного образования
21513,0,-1166.216789,35,среднее,1,женат / замужем,0,F,сотрудник,0,250986.142309,покупка жилья
21514,0,-280.469996,27,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,355988.407188,строительство недвижимости
21515,1,-467.685130,28,среднее,1,женат / замужем,0,F,сотрудник,1,109486.327999,заняться образованием
21516,0,-914.391429,42,высшее,0,женат / замужем,0,F,компаньон,0,322807.776603,покупка своего жилья
21517,0,-404.679034,42,высшее,0,гражданский брак,1,F,компаньон,0,178059.553491,на покупку своего автомобиля
21519,1,-2351.431934,37,ученая степень,4,в разводе,3,M,сотрудник,0,115949.039788,покупка коммерческой недвижимости
21520,1,-4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791.862382,операции с жильем
21522,1,-2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672.561153,недвижимость
21523,3,-3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093.050500,на покупку своего автомобиля
21524,2,-1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047.418899,на покупку автомобиля

In [81]:
data[data['days_employed'] > 0]

,children,days_employed,dob_days,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
24,1,338551.952911,57,среднее,1,Не женат / не замужем,4,F,пенсионер,0,290547.235997,операции с коммерческой недвижимостью
25,0,363548.489348,67,среднее,1,женат / замужем,0,M,пенсионер,0,55112.757732,покупка недвижимости
30,1,335581.668515,62,среднее,1,женат / замужем,0,F,пенсионер,0,171456.067993,операции с коммерческой недвижимостью
35,0,394021.072184,68,среднее,1,гражданский брак,1,M,пенсионер,0,77805.677436,на проведение свадьбы
50,0,353731.432338,63,среднее,1,женат / замужем,0,F,пенсионер,0,92342.730612,автомобили
56,0,370145.087237,64,среднее,1,вдовец / вдова,2,F,пенсионер,0,149141.043533,образование
71,0,338113.529892,62,среднее,1,женат / замужем,0,F,пенсионер,0,43929.696397,автомобили
78,0,359722.945074,61,высшее,0,женат / замужем,0,M,пенсионер,0,175127.646000,сделка с автомобилем
86,0,383933.549664,64,среднее,1,гражданский брак,1,M,пенсионер,0,243033.453281,свадьба
87,0,337659.535004,53,среднее,1,женат / замужем,0,F,пенсионер,0,74363.856554,покупка жилья для сдачи
88,0,373129.789654,63,высшее,0,гражданский брак,1,F,пенсионер,0,206872.350061,на проведение свадьбы
98,0,364906.205736,54,высшее,0,женат / замужем,0,F,пенсионер,0,199707.298524,покупка жилья для сдачи
99,0,346541.618895,0,Среднее,1,женат / замужем,0,F,пенсионер,0,71291.522491,автомобиль
101,0,391558.961849,65,среднее,1,женат / замужем,0,F,пенсионер,0,157970.486393,на покупку своего автомобиля
104,0,366323.649429,59,среднее,1,Не женат / не замужем,4,F,пенсионер,0,163581.950073,покупка жилья для сдачи
119,0,382189.129056,60,среднее,1,Не женат / не замужем,4,F,пенсионер,0,31534.750497,покупка коммерческой недвижимости
128,0,379035.920619,67,среднее,1,в разводе,3,F,пенсионер,0,112331.787067,сделка с автомобилем
129,0,361010.321350,61,среднее,1,гражданский брак,1,M,пенсионер,0,103644.932547,автомобиль
133,0,344507.392785,64,среднее,1,женат / замужем,0,F,пенсионер,0,79047.653059,образование
136,0,357880.159379,60,начальное,3,женат / замужем,0,M,пенсионер,0,113124.202781,операции со своей недвижимостью
142,0,347947.835507,54,среднее,1,женат / замужем,0,F,пенсионер,0,108280.644857,сделка с подержанным автомобилем
150,0,393711.519923,71,среднее,1,гражданский брак,1,F,пенсионер,0,174088.293221,сыграть свадьбу
156,0,362366.857165,65,Среднее,1,женат / замужем,0,M,пенсионер,0,261291.036453,получение дополнительного образования
157,0,348414.028009,38,среднее,1,женат / замужем,0,F,пенсионер,1,113560.650035,сделка с автомобилем
159,0,371052.696813,59,среднее,1,Не женат / не замужем,4,F,пенсионер,0,149542.858874,на покупку своего автомобиля
168,0,361970.220505,67,среднее,1,вдовец / вдова,2,F,пенсионер,0,139038.944645,покупка своего жилья
169,0,372110.892953,58,среднее,1,гражданский брак,1,F,пенсионер,0,167861.700776,приобретение автомобиля
176,0,364178.254930,60,среднее,1,женат / замужем,0,F,пенсионер,0,104621.067411,заняться высшим образованием
...,...,...,...,...,...,...,...,...,...,...,...,...
21347,0,359178.660539,56,среднее,1,гражданский брак,1,M,пенсионер,0,133360.976240,сыграть свадьбу
21356,0,371228.000467,66,высшее,0,женат / замужем,0,M,пенсионер,0,108118.840760,покупка жилой недвижимости
21359,0,333472.211583,63,среднее,1,женат / замужем,0,M,пенсионер,0,89275.261302,покупка жилья для сдачи
21371,0,365582.441708,58,среднее,1,женат / замужем,0,F,пенсионер,0,99249.076469,операции с жильем
21372,0,351181.854112,57,среднее,1,женат / замужем,0,F,пенсионер,0,134910.825327,покупка жилой недвижимости
21378,0,401256.745090,59,среднее,1,вдовец / вдова,2,F,пенсионер,0,204103.704870,операции со своей недвижимостью
21381,0,367527.086044,59,высшее,0,женат / замужем,0,F,пенсионер,1,200883.572649,операции с коммерческой недвижимостью
21385,0,358631.713433,71,среднее,1,женат / замужем,0,F,пенсионер,0,41411.827438,профильное образование
21393,0,390521.534349,65,среднее,1,в разводе,3,F,пенсионер,0,81253.943646,покупка жилья для семьи
21395,0,339994.934957,57,среднее,1,женат / замужем,0,F,пенсионер,0,110084.013555,приобретение автомобиля
21398,0,358105.919392,55,СРЕДНЕЕ,1,Не женат / не замужем,4,F,пенсионер,0,89194.369579,строительство жилой недвижимости
21401,0,389336.706186,67,среднее,1,женат / замужем,0,F,пенсионер,0,90458.607961,покупка жилья для семьи
21402,0,365328.535961,59,среднее,1,гражданский брак,1,F,пенсионер,0,65122.327463,недвижимость
21405,1,389656.256701,66,среднее,1,Не женат / не замужем,4,F,пенсионер,0,223193.335683,операции с жильем
21419,0,362239.529287,67,среднее,1,женат / замужем,0,F,пенсионер,0,130801.622483,строительство недвижимости
21424,0,335228.897103,55,среднее,1,в разводе,3,F,пенсионер,1,237992.543532,покупка жилья для семьи
21433,0,390732.056745,57,среднее,1,гражданский брак,1,F,пенсионер,0,139742.106467,на проведение свадьбы
21441,0,392681.055781,61,среднее,1,в разводе,3,F,пенсионер,0,92924.821176,образование
21444,0,353746.631038,57,Среднее,1,вдовец / вдова,2,F,пенсионер,0,78441.353332,автомобили
21450,0,353581.883314,67,среднее,1,женат / замужем,0,F,пенсионер,0,91630.165501,недвижимость
21467,0,338060.788569,59,среднее,1,женат / замужем,0,F,пенсионер,0,47388.936884,получение образования
21475,0,365213.306266,52,среднее,1,женат / замужем,0,F,пенсионер,1,48239.310903,свой автомобиль
21485,0,363996.449108,59,высшее,0,женат / замужем,0,F,пенсионер,0,267000.734155,на покупку подержанного автомобиля
21501,0,334343.096304,57,среднее,1,женат / замужем,0,F,пенсионер,0,86232.126549,жилье
21504,0,355235.728158,68,среднее,1,женат / замужем,0,F,пенсионер,0,80566.321329,дополнительное образование
21505,0,338904.866406,53,среднее,1,гражданский брак,1,M,пенсионер,0,75439.993167,сыграть свадьбу
21508,0,386497.714078,62,среднее,1,женат / замужем,0,M,пенсионер,0,72638.590915,недвижимость
21509,0,362161.054124,59,высшее,0,женат / замужем,0,M,пенсионер,0,73029.059379,операции с недвижимостью
21518,0,373995.710838,59,СРЕДНЕЕ,1,женат / замужем,0,F,пенсионер,0,153864.650328,сделка с автомобилем
21521,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999.806512,сделка с автомобилем

In [82]:
data[data['days_employed'] > 0]['income_type'].value_counts()

пенсионер      3443
безработный       2
Name: income_type, dtype: int64

In [83]:
data[data['days_employed'] > 0]['days_employed'].describe()

count      3445.000000
mean     365004.309916
std       21075.016396
min      328728.720605
25%      346639.413916
50%      365213.306266
75%      383246.444219
max      401755.400475
Name: days_employed, dtype: float64

In [84]:
data[data['days_employed'] > 0]['days_employed'].describe()

count      3445.000000
mean     365004.309916
std       21075.016396
min      328728.720605
25%      346639.413916
50%      365213.306266
75%      383246.444219
max      401755.400475
Name: days_employed, dtype: float64

In [85]:
female_retire = data[(data['days_employed'] > 0) & (data['gender'] == "F")]
female_retire.describe()

,children,days_employed,dob_days,education_id,family_status_id,debt,total_income
count,2807.000000,2807.000000,2807.000000,2807.000000,2807.000000,2807.000000,2807.000000
mean,0.121838,365401.887646,59.173139,0.924831,1.085857,0.049163,134063.014984
std,0.970398,20950.356291,7.425512,0.503424,1.345554,0.216246,77748.644220
min,-1.000000,328728.720605,0.000000,0.000000,0.000000,0.000000,20667.263793
25%,0.000000,347130.256555,56.000000,1.000000,0.000000,0.000000,81200.848724
50%,0.000000,366206.050748,60.000000,1.000000,0.000000,0.000000,115824.466976
75%,0.000000,383541.818802,63.000000,1.000000,2.000000,0.000000,165730.931013
max,20.000000,401755.400475,74.000000,4.000000,4.000000,1.000000,735103.270167

Похоже, для разного пола данные похожи

In [86]:
# заполним пропуски среднем стажем, плюс стажем в этом столбце, разделенном на 100
data.loc[data['days_employed'] > 0, 'days_employed'] = data.loc[data['days_employed'] > 0,
                                                                'days_employed'] / 100 + data[data['days_employed'] < 0]['days_employed'].abs().mean()
data.loc[data['days_employed'] < 0,'days_employed']  = data.loc[data['days_employed'] < 0,'days_employed'].abs()

In [94]:
data['days_employed'].describe()

count    19351.000000
mean      3002.822065
std       2514.324562
min         24.141633
25%        927.009265
50%       2194.220567
75%       5537.882441
max      18388.949901
Name: days_employed, dtype: float64

### Где и зачем использовать конструкцию try-except?

In [87]:
try:
    data_right = pd.read_csv('data.csv', delimiter='\t')
    data_right.info()
except:
    print("File not found")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       19351 non-null float64
dob_days            21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        19351 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

In [88]:
try:
    data_wrong = pd.read_csv('data_nonexistent_path.csv', delimiter='\t')
    data_wrong.info()
except:
    print("File not found")

File not found

In [89]:
my_series = pd.Series([1, 2, 3, 4])
try:
    print(my_series.mean())
except:
    print("Error applying mean")

2.5

In [90]:
lemm_home_dict = {
  'покупка жилья': 'жилье',
  'операции с жильем': 'жилье',
  'покупка жилья для семьи': 'жилье',
  'жилье': 'жилье',
  'покупка своего жилья': 'жилье',
  'покупка жилья для сдачи': 'жилье',
  'ремонт жилью':'жилье'
}

def home_category(some_string):
    try:
        return lemm_home_dict[some_string]
    except:
        return "no_category"

In [91]:
home_category('ремонт дома')

'no_category'

### Аналитические выводы


**_<span style="color:red">Частые недочеты:</span>_**

– разница в процентах одинаковая и в детях, и в семейном положении, но в одном случае она интерпретируется как значимая, в другом нет;

– путаница в формулировках для долей и абсолютах (большинство = большинство абсолютное, наибольшая доля = большинство в процентах);

– хорошая лексика – "есть зависимость", "есть риски для банка"

**_<span style="color:green">Желательно:</span>_**

– рекоммендации для заказчика (для клиентов в группах риска собрать больше данных о платежеспособности)

– советы для заказчика (исследовать неконсистентность)

### Ссылки

Видео на русском о квантилях https://ru.coursera.org/lecture/znakomstvo-r-bazovaya-statistika/miediana-i-kvantili-Tj9Lf

Дока `pandas` о метода `quantile` https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.quantile.html